on:
    push:
        branches:
            - main

jobs:
    get-changed-files:
        runs-on: ubuntu-latest
        outputs:
            all_changed_files: ${{ steps.changed-files-step.outputs.all_changed_files }}
            any_file_changed: ${{ steps.changed-files-step.outputs.any_changed }}
        steps:
            - uses: actions/checkout@v4
            - name: Get changed files
              id: changed-files-step
              uses: tj-actions/changed-files@v44
              with:
                files: '**/*.tsp'


    trigger-package-generation:
        needs: [get-changed-files]
        runs-on: ubuntu-latest
        if: needs.get-changed-files.outputs.any_file_changed == 'true'
        steps:
            - uses: actions/checkout@v4
            - name: print-files
              env:
                ALL_CHANGED_FILES: ${{ needs.get-changed-files.outputs.all_changed_files }}
              run: |
                for file in ${ALL_CHANGED_FILES}; do
                    echo "$file was changed"
                done
            - name: install
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
                cache-dependency-path: ${{github.workspace}}/package-lock.json
            - run: npm i
            - uses: actions/checkout@v4
            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                java-version: '21'
                distribution: 'temurin'
            - run: |
                for file in ${ALL_CHANGED_FILES}; do
                  tsp compile $file
                  content=$(<templates/pom-tmpl.xml)

                  api_domain=$(echo $file | sed -n 's|\([^/]*\)/.*|\1|p')
                  export api_domain

                  echo $content | envsubst > "pom-tmpl.xml"

                  mvn clean compile -f "pom-tmpl.xml"
                  
                  mvn deploy -s settings.xml -f pom-tmpl.xml
                done
